// Package schema
// Automatically generated by gen_structs.go, DO NOT EDIT manually
package schema

type Base struct {
	ID             string `json:"id"`
	CollectionID   string `json:"collectionId"`
	CollectionName string `json:"collectionName"`
	Created        string `json:"created"`
	Updated        string `json:"updated"`
}

type CrawlEvent struct {
	Base
	Status   string `json:"status"`
	Data     string `json:"data"`
	Checksum string `json:"checksum"`
}

type CrawlNotifier struct {
	Base
	NotifyMethod   string `json:"notify_method"`
	NotifyTemplate string `json:"notify_template"`
}

type CrawlTarget struct {
	Base
	Name      string `json:"name"`
	Url       string `json:"url"`
	Selector  string `json:"selector"`
	Type      string `json:"type"`
	LastCrawl string `json:"last_crawl"`
	IsActive  bool   `json:"is_active"`
}
